 main: com.enteente.plotborder.Main
 name: plotborder
 version: 0.3.1
 author: schubc
 description: Change borders of plotsquared plots
 commands:
     plotborder:
        description: change plot border
        usage: /pb <border|wall|reload> <type>
        aliases: [pb, pborder]